// La biblioteca: una entrada por cosa que llega del programa. Para agregar
// algo, se suma una entrada a `library` (ver el tipo `Entry` en schema.ts).
// El resumen dice, corto, qué hace o qué enseña.
import { CONTRACT_TESTS, ORIGINAL, REPO, TTL_DAYS, explorer } from "@/lib/deployment";
import { formatXlm } from "@/lib/format";
import { MIN_INVESTMENT, RWA_REPO, RWA_RUN, RWA_TESTS, RWA_UPSTREAM } from "@/lib/rwa-deployment";
import { kosmovia } from "./kosmovia";
import type { Entry } from "./schema";

const EXPLICACION = "/tareas/aex-pass/explicacion";
const STELLAR_BUILD = "https://github.com/latmontecinos-sketch/Stellar-Build";
const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;

/** Una clase grabada en YouTube. */
function clase(
  id: string,
  title: string,
  video: string,
  date: string,
  week: number,
  order: number,
  author: string,
  summary: string,
  tags: string[],
  extra: Partial<Entry> = {},
): Entry {
  return {
    id,
    title,
    kind: "clase",
    summary,
    tags,
    links: [{ label: "YouTube", href: yt(video) }],
    author,
    video,
    date,
    week,
    order,
    ...extra,
  };
}

export const library: Entry[] = [
  // ── Clases y videos ────────────────────────────────────────────────
  clase(
    "semana-1-introduccion",
    "Sesión de introducción",
    "NyapZNr0qQM",
    "2026-09-04",
    1,
    1,
    "Emmi",
    "La sesión que abre Stellar Elite Bolivia. El video no tiene subtítulos, así que todavía no tiene resumen.",
    ["Introducción"],
  ),
  clase(
    "semana-1-sesion-3",
    "Sesión 3: Introducción",
    "EvP1kuw4eNs",
    "2026-09-05",
    1,
    2,
    "Emmi",
    "Cómo ganar experiencia, y a veces pagos, con código abierto en GrantFox y Drips, y cómo Stellar Build ayuda a validar una idea para Stellar con agentes de IA.",
    ["Código abierto", "Stellar Build", "SCF"],
  ),
  clase(
    "semana-2-sesion-1",
    "Sesión 1: Producto",
    "6gXEagoi7xc",
    "2026-09-07",
    2,
    1,
    "Emmi",
    "Aprender del cliente antes de construir: supuestos, entrevistas a usuarios, cómo definir bien el problema, arquetipos, MVP y formas de financiar un producto.",
    ["Producto", "Entrevistas", "MVP"],
  ),
  clase(
    "semana-2-sesion-2",
    "Sesión 2: Producto",
    "k6KfyUGna7Y",
    "2026-09-08",
    2,
    2,
    "Emmi",
    "De lo que aprendiste del cliente a qué construir: el valor, el ajuste problema-solución, el alcance del MVP, los documentos para la IA y por qué lanzar rápido.",
    ["Producto", "MVP", "PRD"],
  ),
  clase(
    "semana-2-sesion-3",
    "Sesión 3: Producto",
    "NGf1Jo4O4g8",
    "2026-09-09",
    2,
    3,
    "Emmi",
    "Cómo llegar a los usuarios con canales y alianzas, medir la tracción y contar la historia del producto para pedir grants o inversión.",
    ["Distribución", "Métricas", "Pitch"],
  ),
  clase(
    "clase-1",
    "Sesión 1: Smart Contracts",
    "fnrLiRpMHXE",
    "2026-09-14",
    3,
    1,
    "Emmi",
    "Qué es un contrato en Stellar: se escribe en Rust, se compila a Wasm y guarda datos en tres tipos de storage. Instala Rust y el Stellar CLI y corre un contrato contador.",
    ["Soroban", "Rust", "Storage"],
  ),
  clase(
    "clase-2",
    "Clase 16/09: Smart Contracts",
    "jJtw_85WJjA",
    "2026-09-16",
    3,
    2,
    "Leonardo Vaca",
    "Cómo un contrato decide quién puede hacer qué (require_auth), maneja estados, errores y eventos. Corrige un bug de autorización, prueba el contrato y lo despliega en testnet.",
    ["Soroban", "Auth", "Tests"],
  ),
  clase(
    "clase-3",
    "Clase 17/09: Smart Contracts",
    "kmq_19PtAzc",
    "2026-09-17",
    3,
    3,
    "Leonardo Vaca",
    "Tokens en Stellar (assets clásicos y contratos de token), oráculos de precio y Solang. Invoca un contrato con el CLI, el UI Builder y Stellar Lab, y presenta el entregable.",
    ["Tokens", "Oráculos", "OpenZeppelin"],
    { task: "aex-pass" },
  ),
  {
    id: "curso-fabian",
    title: "Las bases del desarrollo en Stellar: el primer smart contract",
    kind: "clase",
    summary: "Curso para repasar desde cero cómo se crea un contrato en Stellar.",
    tags: ["Curso", "Soroban"],
    links: [{ label: "YouTube", href: yt("uyTsLnzYgFs") }],
    author: "Fabián Sánchez",
    video: "uyTsLnzYgFs",
    date: "2026-09-17",
    week: 3,
    order: 4,
  },
  clase(
    "semana-4-sesion-2",
    "Sesión 2: Front-end y Back-end",
    "QIjwNNl13QY",
    "2026-09-27",
    4,
    2,
    "Emmi",
    "Cómo conectar un contrato de token con una web: llamar sus funciones, firmar con Freighter y mostrar los errores del contrato en palabras que el usuario entienda.",
    ["Frontend", "Freighter", "SEP-41"],
  ),
  clase(
    "semana-4-clase-25",
    "Clase 25/09: Front-end y Back-end",
    "C3Zj462nkNA",
    "2026-09-25",
    4,
    3,
    "Ady",
    "Cómo comprobar quién es el dueño de una wallet (también con passkeys), guardar datos en caché con Redis y armar un backend que prepara transacciones para firmar.",
    ["Backend", "Wallets", "Passkeys"],
  ),
  clase(
    "semana-5-sesion-1",
    "Sesión 1: Vibecoding e IA",
    "d5OWaSqWR3I",
    "2026-09-28",
    5,
    1,
    "Emmi",
    "Del vibecoding a programar con IA en serio: planificar antes de pedir código, revisar lo que hace el agente y entender los tokens y la ventana de contexto.",
    ["IA", "Planificación"],
  ),
  clase(
    "clase-vibe-coding",
    "Sesión 2 y 3: Vibecoding e IA",
    "OvesLVcciKE",
    "2026-10-01",
    5,
    2,
    "Emmi",
    "Brandon, autor de stellar-expert-mcp y reflector-skill, arma desde cero una app para cambiar cripto entre personas (OTC) en Stellar, con Cursor, MCPs, skills y un plan por fases.",
    ["IA", "MCP", "Skills"],
  ),

  // ── Mis apuntes ────────────────────────────────────────────────────
  {
    id: "anatomia-contrato",
    title: "Anatomía de un contrato Soroban",
    kind: "apunte",
    summary:
      "Las partes de un contrato: #[contract] y #[contractimpl], el constructor que corre una vez, el storage (instance y persistent), los errores tipados y los eventos.",
    tags: ["Soroban", "Rust"],
    links: [{ label: "Ver en Aex Pass", href: `${EXPLICACION}#funciones` }],
    date: "2026-09-22",
    week: 4,
    order: 1,
    task: "aex-pass",
  },
  {
    id: "require-auth",
    title: "Autorización con require_auth",
    kind: "apunte",
    summary:
      "Cómo un contrato exige la firma de una cuenta, y por qué un rol como el anfitrión se lee del storage y no de un parámetro: así nadie se hace pasar por él.",
    tags: ["Soroban", "Seguridad"],
    links: [{ label: "Ver en Aex Pass", href: `${EXPLICACION}#reglas` }],
    date: "2026-09-22",
    week: 4,
    order: 2,
    task: "aex-pass",
  },
  {
    id: "simular",
    title: "Simular antes de enviar",
    kind: "apunte",
    summary:
      "Cada transacción se simula antes de enviarse: si falla, no se envía ni se cobra. Las lecturas solo se simulan, así que no cuestan.",
    tags: ["Stellar CLI", "stellar-sdk"],
    links: [{ label: "Ver en Aex Pass", href: `${EXPLICACION}#errores` }],
    date: "2026-09-22",
    week: 4,
    order: 3,
    task: "aex-pass",
  },
  {
    id: "renta-ttl",
    title: "Renta y TTL del storage",
    kind: "apunte",
    summary: `Cada dato guardado vence (TTL) y mantenerlo cuesta renta. Mi primera compra costó ${formatXlm(ORIGINAL.buy.feeStroops, 2)} XLM por extenderlo ${TTL_DAYS} días: conviene ajustar el plazo al evento.`,
    tags: ["Soroban", "Costos"],
    links: [{ label: "Ver en Aex Pass", href: `${EXPLICACION}#costos` }],
    date: "2026-09-22",
    week: 4,
    order: 4,
    task: "aex-pass",
  },
  {
    id: "comandos-cli",
    title: "Comandos esenciales del Stellar CLI",
    kind: "apunte",
    summary:
      "Qué hace cada uno: keys generate --fund crea una cuenta de prueba, contract build compila, contract deploy publica y contract invoke llama (con --send=no solo simula).",
    tags: ["Stellar CLI"],
    links: [{ label: "Ver la ejecución completa", href: "/tareas/aex-pass/ejecucion" }],
    date: "2026-09-22",
    week: 4,
    order: 5,
    task: "aex-pass",
  },
  {
    id: "leer-transaccion",
    title: "Leer una transacción en stellar.expert",
    kind: "apunte",
    summary:
      "Dónde ver, en una transacción, el contrato que se invocó, las transferencias, los eventos, lo que cambió en el storage y la comisión.",
    tags: ["Explorador"],
    links: [{ label: "Ejemplo: la compra de Aex Pass", href: explorer.tx(ORIGINAL.buy.tx) }],
    date: "2026-09-22",
    week: 4,
    order: 6,
    task: "aex-pass",
  },

  // ── Documentación ──────────────────────────────────────────────────
  {
    id: "docs-contratos",
    title: "Contratos inteligentes en Stellar",
    kind: "documentacion",
    summary: "La guía oficial para escribir, probar y desplegar contratos. El punto de partida.",
    tags: ["Oficial", "Soroban"],
    links: [{ label: "developers.stellar.org", href: "https://developers.stellar.org/docs/build/smart-contracts" }],
    date: "2026-09-15",
    week: 3,
    order: 1,
  },
  {
    id: "docs-assets",
    title: "Assets: panorama y comparación",
    kind: "documentacion",
    summary: "Qué es un asset en Stellar y cuándo usar un asset clásico o un token de contrato.",
    tags: ["Oficial", "Assets"],
    links: [{ label: "developers.stellar.org", href: "https://developers.stellar.org/docs/tokens/anatomy-of-an-asset" }],
    date: "2026-09-17",
    week: 3,
    order: 2,
  },
  {
    id: "docs-sac",
    title: "Desplegar el Stellar Asset Contract (SAC)",
    kind: "documentacion",
    summary: "Cómo usar un asset clásico, como XLM o USDC, desde un contrato. Así cobra Aex Pass en XLM.",
    tags: ["Oficial", "Stellar CLI", "Assets"],
    links: [
      {
        label: "developers.stellar.org",
        href: "https://developers.stellar.org/docs/tools/cli/cookbook/deploy-stellar-asset-contract",
      },
    ],
    date: "2026-09-17",
    week: 3,
    order: 3,
  },
  {
    id: "docs-openzeppelin",
    title: "OpenZeppelin para Stellar",
    kind: "documentacion",
    summary: "Contratos auditados listos para usar: tokens, permisos, pausas y actualizaciones. Para no reinventar lo básico.",
    tags: ["Seguridad", "Tokens"],
    links: [
      { label: "En Stellar Docs", href: "https://developers.stellar.org/docs/tools/openzeppelin-contracts" },
      { label: "Documentación de OpenZeppelin", href: "https://docs.openzeppelin.com/stellar-contracts" },
    ],
    date: "2026-09-17",
    week: 3,
    order: 4,
  },
  {
    id: "docs-seps",
    title: "Stellar Ecosystem Proposals (SEPs)",
    kind: "documentacion",
    summary: "Los estándares que hacen que wallets, anclas y apps de Stellar se entiendan entre sí.",
    tags: ["Oficial", "Estándares"],
    links: [
      {
        label: "developers.stellar.org",
        href: "https://developers.stellar.org/docs/learn/fundamentals/stellar-ecosystem-proposals",
      },
    ],
    date: "2026-09-21",
    week: 4,
    order: 6,
  },
  {
    id: "docs-bindings",
    title: "Generar bindings de TypeScript",
    kind: "documentacion",
    summary: "Cómo generar un cliente TypeScript de tu contrato para llamarlo desde el frontend.",
    tags: ["Oficial", "Frontend", "TypeScript"],
    links: [{ label: "developers.stellar.org", href: "https://developers.stellar.org/docs/build/apps/guestbook/bindings" }],
    date: "2026-09-21",
    week: 4,
    order: 7,
  },
  {
    id: "soroban-sdk-docs",
    title: "Referencia de soroban-sdk",
    kind: "documentacion",
    summary: "La referencia de la librería de Rust para contratos: tipos, storage, auth, tokens y eventos.",
    tags: ["Rust"],
    links: [{ label: "docs.rs", href: "https://docs.rs/soroban-sdk" }],
    date: "2026-09-22",
    week: 4,
    order: 8,
  },
  {
    id: "trustless-blocks",
    title: "Trustless Work: Escrow Blocks",
    kind: "documentacion",
    author: "Trustless Work",
    summary:
      "Componentes de React para sumar pagos con escrow a una app Next.js. Se instalan con su CLI y están pensados para armar la app con IA.",
    tags: ["Escrow", "React", "IA"],
    links: [
      {
        label: "Guía de vibe coding",
        href: "https://docs.trustlesswork.com/trustless-work/ai/vibe-coding-or-blocks-sdk",
      },
    ],
    date: "2026-10-01",
    week: 5,
    order: 0,
    session: "clase-vibe-coding",
  },
  {
    id: "stripe-stablecoins",
    title: "Stripe y las stablecoins",
    kind: "documentacion",
    author: "Stripe",
    summary:
      "Stripe deja cobrar, guardar y enviar USDC, y Stellar es una de sus redes. Guardar saldo en USDC está en acceso anticipado para Bolivia: se pide con un formulario.",
    tags: ["USDC", "Pagos", "Stablecoins"],
    links: [
      { label: "docs.stripe.com", href: "https://docs.stripe.com/stablecoins" },
      { label: "Redes soportadas", href: "https://docs.stripe.com/treasury/transfer-send#stablecoin-assets" },
    ],
    date: "2026-10-01",
    week: 5,
    order: 9,
  },

  // ── Repositorios ───────────────────────────────────────────────────
  {
    id: "aex-pass",
    title: "Aex Pass",
    kind: "repositorio",
    origin: "mio",
    summary: `Mi contrato de pases para un evento: el pase se compra una vez y se usa una vez. Con ${CONTRACT_TESTS} pruebas y la demo del Stellar CLI.`,
    tags: ["Soroban", "Rust", "Testnet"],
    links: [
      { label: "GitHub", href: REPO },
      { label: "Contrato", href: explorer.contract(ORIGINAL.contract) },
    ],
    date: "2026-09-22",
    week: 4,
    order: 1,
    task: "aex-pass",
  },
  {
    id: "rwa-launchpad-fork",
    title: "RWA Launchpad (mi fork)",
    kind: "repositorio",
    origin: "mio",
    summary: `Mi versión del launchpad del bootcamp: exige invertir al menos ${MIN_INVESTMENT}, o falla con AmountTooLow. Con ${RWA_TESTS} tests y scripts para testnet.`,
    tags: ["Soroban", "Rust", "RWA", "Testnet"],
    links: [
      { label: "GitHub", href: RWA_REPO },
      { label: "Contrato", href: explorer.contract(RWA_RUN.contract) },
    ],
    date: "2026-09-28",
    week: 4,
    order: 0,
    task: "rwa-launchpad",
  },
  {
    id: "kosmovia",
    title: "Kosmovia",
    kind: "repositorio",
    origin: "mio",
    summary:
      "La red social para el ecosistema Stellar que construyo con mi equipo: comunidades, un muro y una billetera integrada. En desarrollo, sobre testnet.",
    tags: ["Equipo", "En desarrollo"],
    links: [
      { label: "GitHub", href: kosmovia.repo },
      { label: "Sitio", href: kosmovia.site },
      { label: "Página", href: "/kosmovia" },
    ],
    date: "2026-09-16",
    week: 3,
    order: 3,
  },
  {
    id: "rwa-launchpad",
    title: "RWA Launchpad (bootcamp)",
    kind: "repositorio",
    origin: "comunidad",
    author: "Oppia Software Labs",
    summary:
      "El repo base del bootcamp: un launchpad que vende tokens de activos reales (RWA) en Soroban, con su frontend en TypeScript.",
    tags: ["Bootcamp", "RWA", "Soroban"],
    links: [{ label: "GitHub", href: RWA_UPSTREAM }],
    date: "2026-09-21",
    week: 4,
    order: 5,
    task: "rwa-launchpad",
  },
  {
    id: "trustless-work",
    title: "Trustless Work: contrato de escrow",
    kind: "repositorio",
    origin: "comunidad",
    author: "Trustless Work",
    summary:
      "Un escrow en producción: guarda USDC hasta que se cumple lo acordado y cualquier plataforma lo puede integrar. Bueno para estudiar un contrato real.",
    tags: ["Escrow", "USDC", "Rust"],
    links: [{ label: "GitHub", href: "https://github.com/Trustless-Work/trustlesswork-smart-contract-stellar" }],
    date: "2026-09-21",
    week: 4,
    order: 6,
  },
  {
    id: "after-stellar",
    title: "afterStellar: Stellar, en criollo",
    kind: "repositorio",
    origin: "comunidad",
    author: "Eli (María Elisa Araya)",
    summary:
      "Los conceptos de Stellar explicados simple, por una dev de la comunidad argentina. Útil si algún concepto todavía cuesta.",
    tags: ["Conceptos", "Principiantes"],
    links: [{ label: "GitHub", href: "https://github.com/mariaelisaaraya/afterStellar" }],
    date: "2026-09-19",
    week: 3,
    order: 7,
  },
  {
    id: "soroban-examples",
    title: "soroban-examples",
    kind: "repositorio",
    origin: "oficial",
    author: "Stellar",
    summary: "Contratos de ejemplo oficiales para estudiar y copiar: tokens, autorización, eventos, storage y más.",
    tags: ["Oficial", "Soroban"],
    links: [{ label: "GitHub", href: "https://github.com/stellar/soroban-examples" }],
    date: "2026-09-22",
    week: 4,
    order: 8,
  },

  // ── Skills e IA ────────────────────────────────────────────────────
  {
    id: "stellar-build",
    title: "Stellar Build: mis 12 skills",
    kind: "skill",
    origin: "mio",
    summary:
      "Las skills de Claude Code del toolkit del programa: contratos, frontend, assets, datos, estándares, mainnet, pagos x402, ZK, ideas, competencia, rondas del SCF y cuál usar. Fue mi primer entregable.",
    tags: ["Claude Code", "Toolkit"],
    links: [
      { label: "Ver las skills", href: `${STELLAR_BUILD}/tree/main/.claude/skills` },
      { label: "Repo", href: STELLAR_BUILD },
    ],
    date: "2026-09-06",
    week: 1,
    order: 1,
  },
  {
    id: "raven",
    title: "Stellar Raven",
    kind: "skill",
    summary:
      "Un MCP que conecta a tu agente de IA con la documentación de Stellar, datos en vivo del ecosistema y guías probadas, con una sola conexión.",
    tags: ["MCP", "IA"],
    links: [{ label: "raven.stellar.buzz", href: "https://raven.stellar.buzz/" }],
    date: "2026-09-21",
    week: 4,
    order: 0,
  },
  {
    id: "skills-stellar",
    title: "Stellar Skills",
    kind: "skill",
    origin: "oficial",
    author: "Stellar",
    summary:
      "El catálogo oficial de skills para que tu agente de IA construya en Stellar: contratos, frontend, assets, RPC, pagos y más, junto con skills de la comunidad.",
    tags: ["Oficial", "IA", "Catálogo"],
    links: [{ label: "skills.stellar.org", href: "https://skills.stellar.org/" }],
    date: "2026-10-01",
    week: 5,
    order: 1,
    session: "clase-vibe-coding",
  },
  {
    id: "openzeppelin-mcp",
    title: "OpenZeppelin MCP: Stellar Contracts",
    kind: "skill",
    origin: "oficial",
    author: "OpenZeppelin",
    summary: "Un MCP que le da a tu agente las plantillas auditadas de OpenZeppelin para generar contratos Soroban seguros.",
    tags: ["MCP", "Seguridad", "IA"],
    links: [{ label: "mcp.openzeppelin.com", href: "https://mcp.openzeppelin.com/" }],
    date: "2026-10-01",
    week: 5,
    order: 2,
    session: "clase-vibe-coding",
  },
  {
    id: "stellar-expert-mcp",
    title: "stellar-expert-mcp",
    kind: "skill",
    origin: "comunidad",
    author: "Bran18",
    summary:
      "Un MCP que le da a tu agente los datos de stellar.expert: assets, cuentas conocidas y datos de la red, sin salir del chat.",
    tags: ["MCP", "Explorador", "IA"],
    links: [{ label: "GitHub", href: "https://github.com/Bran18/stellar-expert-mcp" }],
    date: "2026-10-01",
    week: 5,
    order: 3,
    session: "clase-vibe-coding",
  },
  {
    id: "reflector-skill",
    title: "reflector-skill",
    kind: "skill",
    origin: "comunidad",
    author: "Bran18",
    summary:
      "Le enseña a tu agente a usar Reflector, el oráculo de precios de Stellar, dentro de un contrato. Se instala con npx skills add Bran18/reflector-skill.",
    tags: ["Oráculo", "Precios", "IA"],
    links: [{ label: "GitHub", href: "https://github.com/Bran18/reflector-skill" }],
    date: "2026-10-01",
    week: 5,
    order: 4,
    session: "clase-vibe-coding",
  },
  {
    id: "pollar",
    title: "Pollar",
    kind: "skill",
    origin: "comunidad",
    author: "Pollar",
    summary:
      "Un SDK para que tus usuarios entren con Google, GitHub o email y tengan wallet sin ver seed phrases: activa la cuenta, crea trustlines, paga las comisiones y mueve USDC. Trae una skill y un MCP para tu agente.",
    tags: ["Onboarding", "Wallets", "USDC", "IA"],
    links: [
      { label: "Documentación", href: "https://docs.pollar.xyz/docs" },
      { label: "GitHub", href: "https://github.com/pollar-xyz/pollar" },
      { label: "Skill", href: "https://github.com/pollar-xyz/pollar/tree/main/skills/pollar-wallet-auth" },
    ],
    date: "2026-10-01",
    week: 5,
    order: 5,
    session: "clase-vibe-coding",
  },

  // ── Herramientas ───────────────────────────────────────────────────
  {
    id: "v0",
    title: "v0",
    kind: "herramienta",
    author: "Vercel",
    summary:
      "Describes la app con palabras y v0 genera el código en Next.js, listo para publicar en Vercel. Rápido para el frontend de un prototipo.",
    tags: ["IA", "Frontend", "Next.js"],
    links: [{ label: "v0.app", href: "https://v0.app/" }],
    date: "2026-10-01",
    week: 5,
    order: 0,
    session: "clase-vibe-coding",
  },
  {
    id: "stellar-cli",
    title: "Stellar CLI",
    kind: "herramienta",
    summary: "La herramienta oficial de terminal para compilar, desplegar e invocar contratos. Uso la versión 28.",
    tags: ["Terminal"],
    links: [{ label: "Manual", href: "https://developers.stellar.org/docs/tools/cli/stellar-cli" }],
    date: "2026-09-22",
    week: 4,
    order: 1,
  },
  {
    id: "stellar-lab",
    title: "Stellar Lab",
    kind: "herramienta",
    summary: "La web oficial para crear cuentas, armar transacciones e invocar contratos sin terminal.",
    tags: ["Oficial", "Web"],
    links: [{ label: "lab.stellar.org", href: "https://lab.stellar.org" }],
    date: "2026-09-22",
    week: 4,
    order: 2,
  },
  {
    id: "stellar-expert",
    title: "stellar.expert",
    kind: "herramienta",
    summary: "El explorador de la red: muestra cuentas, transacciones, contratos, eventos y storage.",
    tags: ["Explorador"],
    links: [{ label: "Testnet", href: "https://stellar.expert/explorer/testnet" }],
    date: "2026-09-22",
    week: 4,
    order: 3,
  },
  {
    id: "rust-wasm",
    title: "Rust + wasm32v1-none",
    kind: "herramienta",
    summary: "Rust es el lenguaje de los contratos; wasm32v1-none es el target que los compila para que corran en la red.",
    tags: ["Rust"],
    links: [{ label: "rustup", href: "https://rustup.rs" }],
    date: "2026-09-22",
    week: 4,
    order: 4,
  },
  {
    id: "stellar-sdk-js",
    title: "@stellar/stellar-sdk",
    kind: "herramienta",
    summary: "El SDK de JavaScript para llamar contratos desde una web. Este sitio lo usa para desplegar e invocar desde el navegador.",
    tags: ["JavaScript"],
    links: [{ label: "npm", href: "https://www.npmjs.com/package/@stellar/stellar-sdk" }],
    date: "2026-09-22",
    week: 4,
    order: 5,
  },

  // ── Comunidad y oportunidades ──────────────────────────────────────
  {
    id: "stellar-bolivia-ig",
    title: "Stellar Bolivia",
    kind: "comunidad",
    summary: "El Instagram de la comunidad en Bolivia: novedades, eventos y convocatorias.",
    tags: ["Bolivia", "Instagram"],
    links: [{ label: "Instagram", href: "https://www.instagram.com/stellar_bolivia/" }],
    date: "2026-09-18",
    week: 3,
    order: 1,
  },
  {
    id: "meridian-2026",
    title: "Meridian 2026 en Lisboa",
    kind: "comunidad",
    summary: "La conferencia anual de Stellar, el 28 y 29 de octubre en Lisboa. La inscripción está abierta.",
    tags: ["Conferencia", "Convocatoria"],
    links: [
      { label: "Sitio oficial", href: "https://meridian.stellar.org" },
      { label: "Convocatoria", href: "https://www.instagram.com/p/DdZRkuZRHrr/" },
    ],
    date: "2026-09-19",
    week: 3,
    order: 2,
  },
  {
    id: "becas-ubc",
    title: "Becas UBC 2026 (BAF)",
    kind: "comunidad",
    author: "BAF",
    summary:
      "Beca de 500 USD más la entrada para la University Blockchain Conference en Austin, el 20 y 21 de noviembre. Las postulaciones cierran el 7 de octubre.",
    tags: ["Beca", "Convocatoria"],
    links: [
      { label: "Postular", href: "https://becas-ubc.vercel.app" },
      { label: "Anuncio", href: "https://x.com/TheBAFNetwork/status/2102182483773018289" },
    ],
    date: "2026-09-21",
    week: 4,
    order: 3,
  },
];
